<a href="https://colab.research.google.com/github/imdoamaral/formacao-pnl/blob/main/classificacao_de_spam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Classificação de Spam

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
from google.colab import files

uploaded = files.upload()

Saving spam.csv to spam.csv

In [3]:
spam = pd.read_csv("spam.csv")
spam.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
spam.shape

(5572, 2)

In [5]:
spam['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [8]:
distribuicao_percentual = spam['Category'].value_counts(normalize=True)
print(distribuicao_percentual)

Category
ham     0.865937
spam    0.134063
Name: proportion, dtype: float64

In [9]:
prev = spam['Message']
classe = spam['Category']

In [10]:
vetorizador = TfidfVectorizer()
previsores = vetorizador.fit_transform(prev)
previsores.shape

(5572, 8709)

In [11]:
print(vetorizador.get_feature_names_out()[0:100])

['00' '000' '000pes' '008704050406' '0089' '0121' '01223585236'
 '01223585334' '0125698789' '02' '0207' '02072069400' '02073162414'
 '02085076972' '021' '03' '04' '0430' '05' '050703' '0578' '06' '07'
 '07008009200' '07046744435' '07090201529' '07090298926' '07099833605'
 '07123456789' '0721072' '07732584351' '07734396839' '07742676969'
 '07753741225' '0776xxxxxxx' '07781482378' '07786200117' '077xxx' '078'
 '07801543489' '07808' '07808247860' '07808726822' '07815296484'
 '07821230901' '078498' '07880867867' '0789xxxxxxx' '07946746291'
 '0796xxxxxx' '07973788240' '07xxxxxxxxx' '08' '0800' '08000407165'
 '08000776320' '08000839402' '08000930705' '08000938767' '08001950382'
 '08002888812' '08002986030' '08002986906' '08002988890' '08006344447'
 '0808' '08081263000' '08081560665' '0825' '083' '0844' '08448350055'
 '08448714184' '0845' '08450542832' '08452810071' '08452810073'
 '08452810075over18' '0870' '08700435505150p' '08700469649'
 '08700621170150p' '08701213186' '08701237397' '08701417012'
 '08701417012150p' '0870141701216' '087016248' '08701752560'
 '087018728737' '0870241182716' '08702490080' '08702840625' '08704050406'
 '08704439680' '08704439680ts' '08706091795' '0870737910216yrs'
 '08707500020' '08707509020']

In [12]:
# `test_size` = percentual de dados que serão usados para o teste,
# o restante será usado para treinamento.

X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(previsores, classe, test_size=0.3)

In [13]:
X_teste.shape

(1672, 8709)

In [16]:
# `n_estimators` define o número de árvores de decisão da floresta.
# Mais árvores melhoram melhoram a precisão do modelo,
# porém o custo computacional será maior.

floresta = RandomForestClassifier(n_estimators=500)  # o valor padrão do n_estimators é 100
floresta.fit(X_treinamento, y_treinamento)

RandomForestClassifier(n_estimators=500)

In [17]:
previsoes = floresta.predict(X_teste)
print(previsoes)

['ham' 'ham' 'ham' ... 'ham' 'ham' 'ham']

In [18]:
# y_teste = o que de fato aconteceu
# previsoes = previsao feita pelo modelo

print(confusion_matrix(y_teste, previsoes))

[[1435    1]
 [  36  200]]

**[VP] [FN]**
<br>
**[FP] [VN]**

* **[VP], [VN]** = acertos
* **[FP]** = não eram Spam e o modelo atribuiu como Spam
* **[VN]** = eram spam e o modelo não atribuiu como Spam

In [19]:
print(accuracy_score(y_teste, previsoes))

0.9778708133971292

In [20]:
print(metrics.classification_report(y_teste, previsoes))

              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      1436
        spam       1.00      0.85      0.92       236

    accuracy                           0.98      1672
   macro avg       0.99      0.92      0.95      1672
weighted avg       0.98      0.98      0.98      1672